name: Update blog posts

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install feedparser
          pip install cairosvg
          echo "설치 완료"

      - name: Generate SVG blog cards
        run: python scripts/generate_svg_cards.py

      - name: Update ReadMe
        run: python scripts/update_readme.py

      - name: Commit and push if changed
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md scripts/svg_cards/*.svg
          git commit -m "FEAT: Update recent blog posts" || echo "No changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:main
